
export const URL = "https://petalchat-imanjithreddy.c9users.io/";

export const NEARBY_POSTS_RECEIVED = "NEARBY_POSTS_RECEIVED";
export const POPULAR_POSTS_RECEIVED = "POPULAR_POSTS_RECEIVED";
export const LATEST_POSTS_RECEIVED = "LATEST_POSTS_RECEIVED";


export const NEARBY_USERS_RECEIVED = "NEARBY_USERS_RECEIVED";
export const ALL_USERS_RECEIVED = "ALL_USERS_RECEIVED";


export const ALL_CHATS_RECEIVED = "ALL_CHATS_RECEIVED";
export const REVEALED_CHATS_RECEIVED = "REVEALED_CHATS_RECEIVED";
export const GROUPS_CHATS_RECEIVED = "GROUPS_CHATS_RECEIVED";

export const USER_DETAILS_RECEIVED = "USER_DETAILS_RECEIVED";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const USER_LOCATION_RECEIVED = "USER_LOCATION_RECEIVED";
export const USER_LOCATION_ERROR = "USER_LOCATION_ERROR";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";
export const JWT_TOKEN = "JWT_TOKEN";
export const FACEBOOK_LOGIN_FAIL = "FACEBOOK_LOGIN_FAIL";
export const ERROR_AUTH_TOKEN = "ERROR_AUTH_TOKEN";

